### ISSUE TITLE
1D Burgers' equation

### ISSUE THREAD

**Issue by gokhalen** [Pressio/pressio-demoapps#122]
Hi -

I am trying to reproduce the results of Lee & Carlberg on the Burgers' equation from the paper "Model reduction of dynamical systems on nonlinear manifolds using deep convolutional autoencoders". At first, I will be satisfied with simple linear subspace Galerkin ROMs with or without hyper-reduction. Later I would like to use autoencoders to compute the manifold. 

I have installed pressio, pressio-demoapps (the tests pass), pressio-tools, pressio4py and pressio-tutorials. 

Where do you think I should start? My C++ is very rusty, rusty enough to be non-existent. I'm more comfortable in Python, so if I could use pressio4py, it would be great. 

Nachiket

**Comment by fnrizzi** [comment]
hi @gokhalen ! thanks for opening this issue!
If you want to use Python: 
- you need to use pressio4py main branch, which is version 0.12.0 (this already contains the compatible pressio to use) 
- the current main branch of pressio4py does support an autoencoder for lspg, see here: https://pressio.github.io/pressio4py/html/md_pages_demos_demo6.html
- since in pressio-demoapps there is no burgers1d so the only thing you need to do would be write your own 1d Burgers problem in a similar way to this : https://github.com/Pressio/pressio4py/blob/main/demos/adv_diff_1d_fom.py

**Comment by fnrizzi** [comment]
I might have a burgers1d problem around, i will take a look and let you know

**Comment by gokhalen** [comment]
I will take a look, thanks for your help.

**Comment by gokhalen** [comment]
> I might have a burgers1d problem around, i will take a look and let you know but in the meantime you can still try to run https://pressio.github.io/pressio4py/html/md_pages_demos_demo6.html since this is an autoencoder

Would [https://github.com/Pressio/pressio-sisc-burgers1d](https://github.com/Pressio/pressio-sisc-burgers1d) be it?

**Comment by gokhalen** [comment]
> I might have a burgers1d problem around, i will take a look and let you know but in the meantime you can still try to run https://pressio.github.io/pressio4py/html/md_pages_demos_demo6.html since this is an autoencoder

I was able to get this to run. 

Nachiket

**Comment by fnrizzi** [comment]
oh great!
